version: 2
jobs:
  build:
    docker: 
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.15
    parallelism: 2

    steps:
      - checkout 
      - run: go build -x 

workflows:
  version: 2
  build-workflow:
    jobs:
      - build