// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Tarefa struct {
	ID      string   `json:"id"`
	Text    string   `json:"text"`
	Feito   bool     `json:"feito"`
	Status  string   `json:"status"`
	Usuario *Usuario `json:"usuario"`
}

type TarefaInput struct {
	ID           string        `json:"id"`
	Text         string        `json:"text"`
	Feito        bool          `json:"feito"`
	Status       string        `json:"status"`
	UsuarioInput *UsuarioInput `json:"usuarioInput"`
}

type Usuario struct {
	ID    string `json:"id"`
	Nome  string `json:"nome"`
	Email string `json:"email"`
}

type UsuarioInput struct {
	ID    string `json:"id"`
	Nome  string `json:"nome"`
	Email string `json:"email"`
}
